language: node_js
node_js:
   - stable

branches:
   only:
      - master

before_script:
   - npm install -g @angular/cli

script:
  - ng build --prod --aot --output-hashing none

# language: node_js
# node_js:
#   - stable
# install:
#  - npm install
# script:
# - npm build_prod_aot
